# server配置
server:
  port: 8800
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

# spring配置
spring:
  application:
    name: core
# TODO 因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  redis:
#    #redis服务器地址
#    host: localhost
#    port: 6379
#    password:
#    database: 0
#    #redis连接超时时间（毫秒）
#    timeout: 18000
#    #lettuce连接池配置 springboot2.x后默认使用Lettuce:
#    #lettuce:
#    jedis:
#      pool:
#        # 连接池最小空闲连接
#        min-idle: 1
#        # 连接池最大空闲连接
#        max-idle: 5
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大空闲连接（使用负值表示没有限制）
#        max-wait: -1

# 日志记录
logging:
  config: classpath:logback.xml
